######################################################################
# Automatically generated by qmake (2.01a) Fri Sep 21 16:26:56 2012
######################################################################

TEMPLATE = app
TARGET = wordCount
QT += core \ 
gui
DEPENDPATH += .
INCLUDEPATH += ../src/

# Input
HEADERS += ../src/Dictionary.h
SOURCES += main.cpp \ 
../src/Dictionary.cpp
