######################################################################
# Automatically generated by qmake (2.01a) Fri Sep 21 16:39:50 2012
######################################################################

TEMPLATE = app
TARGET = spellCheck
QT += core \
gui
DEPENDPATH += .
INCLUDEPATH += ../src/

# Input
HEADERS += ../src/Dictionary.h
SOURCES += main.cpp \
../src/Dictionary.cpp
